config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admini', as: 'rails_admin'
  get 'registrations/after_sign_up_path_for'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "registrations", invitations: "invitations" }

  authenticated :user do
    root to: 'invoices#index', as: :dashboard
  end

  root to: 'pages#home'

  resource :freelancer
  resource :client, only: [:show, :edit, :update, :destroy]

  namespace :client do
    resources :invoices, only: [:index, :show, :create] do
      resource :payment, only: [:create, :new]
    end
  end

  resources :invoices do
    member do
      get :edit_email
      post :send_email
    end
  end
  resources :pages

  authenticate :user, lambda { |u| u.admin  } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  # Newsfeed gem
  include PublicActivity::Model
  # ----
  belongs_to :freelancer
  belongs_to :client
  has_many :transitions, class_name: "InvoiceTransition", autosave: false
  has_many :descriptions, dependent: :destroy

  before_destroy :destroy_activity
  after_create :create_activity_
  after_update :update_activity

  accepts_nested_attributes_for :client
  accepts_nested_attributes_for :descriptions, reject_if: :all_blank

  # validates :invoice_nr, presence: true

  # This method is called now from the invoice controller with an if statement,
  # id the client is existing, we send it the invoice, else we sent him the invitable
  # after_create :send_invoice_by_email

  def self.freelance_invoices(freelance)
    @invoices = freelance.freelancer.invoices
  end

  # This is done to give some state to each invoice and tell the freelancer what is it.
  def state_machine
    @state_machine ||= InvoiceStateMachine.new(self, transition_class: InvoiceTransition,
                                                      association_name: :transitions)
  end

  # optionally delegating some methods
  delegate :can_transition_to?, :transition_to!, :transition_to, :current_state,
          to: :state_machine
  # After the invoice gets created do:


  def send_invoice_by_email!(text)
    # Calling method in user_mailer.rb, delivers later so user doesn't have to wait
    UserMailer.send_invoice_client(self.id, text).deliver_later
    self.email_sent_at = Time.now
    log_activity :sent
    save
  end

  def destroy_activity
    log_activity :destroy
  end

  def update_activity
    log_activity :update
  end

  def create_activity_
    log_activity :create
  end

# ------------------------------- STRIPE ---------------------------------------

def pay(params)
   @price_cents = self.descriptions.last.price_cents

  if self.current_state == "pending"
    charge = using_stripe(self.freelancer) do
      # if self.client.stripe_customer_id.empty?

      #   customer = Stripe::Customer.create(
      #     source: params[:stripeToken],
      #     email:  params[:stripeEmail]
      #     )
      #   self.client.update(stripe_customer_id: customer.id)
      # end

      Stripe::Charge.create(
        # customer:     self.client.stripe_customer_id,   # You should store this customer id and re-use it.
        # Send the source token instead of the customer id.
        # Doesn't store the customers on the Stripe platform
        source: params[:stripeToken],
        amount:       @price_cents, # in cents
        description:  "Payment for invoice #{self.invoice_nr} to client #{self.client.first_name}",
        currency:     'eur'
        )
    end

    if charge # TODO if charge is successful
      self.transition_to!("paid")
      self.update(payment: charge.to_json)
      log_activity :paid
      return true
    end
  end
end

# ------------------------------------------------------------------------------

  #protected

  def log_activity(type)
    create_activity(
      key: "invoice.#{type}",
      owner: freelancer.user, # Proc.new{ |controller, model| controller.try(:current_user) || freelancer },
      parameters:{ client_name: client.first_name, client_last_name: client.last_name, company: client.company }
    )
  end
end

app/controllers/client/invoices_controller.rb
class Client::InvoicesController < ApplicationController

  # before_action :authorize
  before_action :set_invoice, only: [:show]

  # TODO show the freelancer the dashboard (/) rootpath when logged-in (see routes)
  def index
    @invoices = current_user.client.invoices
  end

  # TODO show a specific Invoice. link_to back, edit
  def show

    # Create PDF
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "invoice #{@invoice.invoice_nr}"   # Excluding ".pdf" extension.
      end
    end
  end

  private

  def is_client?
    # returns an array, if is empty, there is no freelancer
    !!(current_user.client)
  end

  def authorize
    redirect_to dashboard_path, alert: "You don't have the rights" unless is_client?
  end

  def set_invoice
    @invoice = current_user.client.invoices.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def invoice_params
    # to set params, think about nested forms (need description and client attributes!)
    params.require(:invoice).permit(:invoice_date, :due_date, :invoice_nr, :invoice_terms)
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :set_invoice, only: [:show, :edit, :update, :destroy, :send_email, :edit_email]

  # TODO show the freelancer the dashboard (/) rootpath when logged-in (see routes)
  def index
    # Redirect client to s/he's own dahsboard
    redirect_to client_invoices_path and return if current_user.client
    @invoices = Invoice.freelance_invoices(current_user)
    @activities = PublicActivity::Activity.where(owner: current_user).order(created_at: 'desc')
  end

  # TODO create a new Invoice (new/create). After create redirect to index.
  def new
    @disable_sidebars = true

    @invoice = Invoice.new
    @invoice.build_client
    @invoice.descriptions.build
    @user = User.new
    @client = Client.new
  end

  def edit_email
  end

  def send_email
    @user = User.where(email: @invoice.client.email).first
    if @user

      @invoice.send_invoice_by_email!(params[:text])
      current_user.freelancer.update(email_text: params[:text]) if params[:save] == '1'
    else
      @user = User.invite_client!({ email: @invoice.client.email }, current_user, {invoice_id: @invoice.id, content: params[:text]})
      @invoice.client.update(user_id: @user.id)
    end
    @invoice.transition_to("pending")
    redirect_to dashboard_path, notice: "Invoice sent to your client #{@invoice.client.first_name}!"
  end

  def create
    @client = Client.where(email: client_params[:email]).first
    @client ||= Client.new(client_params)

    if @client.save
      update_user_client

      @invoice = Invoice.create!(invoice_params.merge(freelancer_id: current_user.freelancer.id, client_id: @client.id))

      if params[:commit] == "Edit email & Send"
        redirect_to edit_email_invoice_path(@invoice), notice: 'Invoice saved'
      else
        redirect_to dashboard_path, notice: "Invoice has been saved waiting to be send"
      end
    else
      @disable_sidebars = true
      @invoice = Invoice.new(invoice_params)
      @invoice.valid?
      @user = User.new
      render :new
    end
  end

  # TODO show a specific Invoice. link_to back, edit
  def show
    @invoice = Invoice.find(params[:id])
    # redirect client to own invoice show
    redirect_to client_invoice_path(@invoice) and return if current_user.client

    #@total = (@invoice.descriptiond.unit  * @invoicce.descriptions.price ) + (@invoice.descriptions.unit * @invoice.descriptions.price * @invoice.descriptions.vat_tax / 100)

    # Create PDF
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "invoice_#{@invoice.invoice_nr}"   # Excluding ".pdf" extension.
      end
    end

  end

  # TODO edit an already existing Invoice (edit/update). Afterward redirect to index
  def edit
    @client = @invoice.client
    @invoice = Invoice.find(params[:id])
  end

  def update
    @invoice = Invoice.find(params[:id])

    # Need to do some refactoring here, but working!
    descriptions = invoice_params[:descriptions_attributes].select{ |k, v| v['_destroy'] == "false" }
    desc_arr_id = invoice_params[:descriptions_attributes].values.select{|h| h[:_destroy] == '1'}.map{|h| h[:id].to_i}
    @invoice.descriptions.where(id: desc_arr_id).destroy_all

    updated_invoice_params = invoice_params.merge!(descriptions_attributes: descriptions)

    @client = @invoice.client
    @client.update(client_params)

    # if @invoice.update(updated_invoice_params)
    #   redirect_to dashboard_path, notice: 'Invoice has been updated.'
    # else
    #   render :edit
    # end

    if params[:commit] == "Edit email & Send"
      redirect_to edit_email_invoice_path(@invoice), notice: 'Invoice saved'
    else
      redirect_to dashboard_path, notice: "Invoice has been saved waiting to be send"
    end

  end

  # TODO destroy a specific Invoice
  def destroy
    @id = @invoice.id
    @invoice.destroy
    @invoices = current_user.freelancer.invoices
    respond_to do |format|
      format.js
    end
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def invoice_params
    # To set params, think about nested forms (need description and client attributes!)
    params.require(:invoice).permit(:invoice_date, :due_date, :invoice_nr, :invoice_terms, :project_description, descriptions_attributes: [:description, :amount, :unit, :vat_tax, :price, :id, :_destroy])
  end

  def client_params
    params.require(:client).permit(:first_name, :last_name, :company, :company_number, :email)
  end

  def update_user_client
    @user = User.where(email: client_params[:email]).first
    @client.update(user_id: @user.id) if @user
  end
end

app/views/invoices/_description_fields.html.erb
<div class="nested-fields">
<div class="row">    <div class="col-xs-12 col-md-5">
    <%= f.input :description, :input_html => {:data => { :'parsley-error-message' => "Description is required please!"}} %>
    </div>
    <div class="col-xs-12 col-md-1">
      <%= f.input :unit, collection: 0..99, :input_html => {:data => { :'parsley-error-message' => "Digit!", :'parsley-type' => "digits", :'parsley-validation-threshold' => "1", :'parsley-trigger' => "keyup" }} %>
    </div>
    <div class="col-xs-12 col-md-2">
      <%= f.input :price, :input_html => {:data => { :'parsley-error-message' => "Price is required please!", :'parsley-type' => "text" }} %>
    </div>
    <div class="col-xs-12 col-md-2">
      <%= f.input :amount, :input_html => {:data => { :'parsley-error-message' => "Amount is required please!", :'parsley-type' => "text" }} %>
    </div>
    <div class="col-xs-12 col-md-1">
      <%= f.input :vat_tax, :input_html => {:data => { :'parsley-error-message' => "VAT is required please!" }} %>
    </div>
    <div class="col-md-1">
       <%= link_to_remove_association f do%>
        <i class="fa fa-trash desc-button" aria-hidden="true" ></i>
       <% end %>
    </div>

</div>

</div>

app/views/invoices/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-9">
      <h1>INVOICE</h1>
      <h6><%= Date.today.to_s %></h6>
    </div>
    <div class="col-xs-12 col-md-3 pull-md-right">
      <div class="freelancer-info text-center">
        <p><strong><%= current_user.freelancer.company_name %></strong></p>
        <p><%= current_user.freelancer.first_name %> <%= current_user.freelancer.last_name %></p>
        <p class="freelancer-info-email"> <%= current_user.email %> </p>
      </div>
    </div>
  </div>

  <%= simple_form_for @invoice, :html => { :class => 'invoice-form', :data => {:'parsley-validate' => ''} } do |f| %>
    <%= f.error_notification %>

    <%= simple_fields_for @client do |c| %>
      <%= client_error_msg = f.error_notification.nil? ? c.error_notification : '' %>
      <div class="client-info">
        <h4>Client info:</h4>

        <div class="row">
          <div class="col-xs-12 col-md-5">
            <%= c.input :first_name, label: 'Client first name', :input_html => {:data => { :'parsley-error-message' => "First Name is required please!", :'parsley-group' => "block1" } }  %>
          </div>
          <div class="col-xs-12 col-md-5">
          <%= c.input :last_name, label: 'Client last name', :input_html => {:data => { :'parsley-error-message' => "Last Name is required please!", :'parsley-group' => "block1" } } %>
          </div>
        </div>

      <%= c.input :company, :input_html => {:data => { :'parsley-error-message' => "Company is required please!" } } %>

      <%= c.input :company_number  %>

      <%= c.input :email, label: 'Client email', placeholder: 'user@domain.com', :html => { :id => 'invoice-email' } %>

    </div>
  <% end %>

  <hr>

  <h4>Description:</h4>

  <div id="descriptions">
    <%= f.input :project_description, label: 'Project description' %>
    <%= f.simple_fields_for :descriptions do |description| %>
      <%= description.error_notification %>
      <%= render 'description_fields', f: description %>
    <% end %>

    <div class="links">
     <div class="plus-button">
        <%= link_to_add_association f, :descriptions do %>
          <span class="glyphicon glyphicon-plus desc-button" aria-hidden="true" id='add-description'></span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="total-fields">
    <div class="row">
      <div class="col-xs-4 col-md-3">
      </div>
      <div class="col-xs-4 col-md-3 pull-right">
        <div><label>Subtotal</label></div>
        <input type="text" id="subtotal" disabled="disabled">
        <div><label>TOTAL</label></div>
        <input type="text" id="total" disabled="disabled">
      </div>
    </div>
  </div>

  <hr>

  <div class="invoice-info">

    <%= f.input :invoice_nr, label: 'Invoice number', :input_html => {:data => { :'parsley-error-message' => "Invoice number is required please!" } } %>
      <div class='row datetimerange'>
        <div class="col-xs-6">
          <%= f.input :invoice_date, as: :date_picker, input_html: {data: {date_options: {defaultDate: Date.today.year.to_s+'/'+Date.today.month.to_s+'/'+Date.today.day.to_s}}} %>
        </div>
        <div class="col-xs-6">
        <%= f.input :due_date, as: :date_picker %>
        </div>
      </div>
    <%= f.input :invoice_terms, label: 'Invoice Terms' %>
  </div>

  <!-- Warning ! if you change Edit email & send OR Save from below make sure to impact changes in the invoices_controller  -->
  <%= f.button :submit, value: "Edit email & Send", :class => 'btn-invoice' %>
  <%= f.button :submit, value: "Save", :class => 'btn-invoice' %>
  <% end %>

</div>

<% content_for(:after_js) do %>
<script type="text/javascript">
  </script>
<% end %>

app/views/invoices/_invoice_show.html.erb
<div class="white-paper">

  <!-- HEADER ROW ---------------------------------- -->

  <div class="inv-header">
    <h3>INVOICE</h3>
    <div class="row">
      <div class="col-xs-12 col-md-8">
        <% if @invoice.freelancer.company_name %>
          <h4> by <%= @invoice.freelancer.company_name %></h4>
        <% else %>
          <h4> by <%= @invoice.freelancer.first_name %> <%= @invoice.freelancer.last_name %></h4>
       <% end %>
      </div>
      <div class="col-xs-12 col-md-2">
        <%= @invoice.invoice_date %>
      </div>
    </div>
  </div>


  <!-- SUMMARY ROW ---------------------------------- -->

  <div class="inv-summary row">
    <div class="hidden-xs hidden-sm col-md-12">
      <div class="row">
        <div class="col-xs-12 col-md-8">
          <h4>INVOICE TO</h4>
        </div>
        <div class="col-xs-12 col-md-4">
          <h4>

          <% total = [] %>
          <%  @invoice.descriptions.all.each do |d| total << d.price_cents end %>
          <%   total.inject(0){|sum, x| sum + x } %>
          <%#=  total[0] %>

          2,500 € TOTAL </h4>

        </div>
      </div>
    </div><!-- hidden-xs col-sm-12 -->
    <div class="inv-sum-client col-xs-12">
      <div class="row">
        <div class="col-xs-12 col-md-8">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <strong>INVOICE TO</strong>
            </div>
            <div class="col-xs-6 col-md-12">
              <% if @invoice.client.company %>
                <h4> <%= @invoice.client.company %></h4>
              <% else %>
                 <h4> <%= @invoice.client.first_name %> <%= @invoice.client.last_name %></h4>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-md-4">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <strong> $TOTAL </strong>
            </div>
            <div class="col-xs-6 col-md-12">
              <h5>due on <%= @invoice.due_date %></h5>
            </div>
          </div>
        </div>
      </div>
    </div><!-- inv-sum-client col-xs-12 -->
  </div><!-- inv-summary row -->





  <!-- DESCRIPTION ROW ---------------------------------- -->

  <div class="inv-description row">
    <div class="nested-fields-header hidden-xs hidden-sm col-md-12">
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <h5>DESCRIPTION</h5>
        </div>
        <div class="col-xs-12 col-md-1">
          <h5>UNIT </h5>
        </div>
        <div class="col-xs-12 col-md-2">
          <h5>PRICE</h5>
        </div>
        <div class="col-xs-12 col-md-1">
          <h5>AMOUNT</h5>
        </div>
        <div class="col-xs-12 col-md-1">
          <h5>VAT</h5>
        </div>
      </div>
    </div><!-- nested-fields-header hidden-xs col-sm-12 -->
    <% @invoice.descriptions.each do |description| %>
      <div class="nested-fields col-xs-12">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <div class="row" >
              <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
                <h5>DESCRIPTION</h5>
              </div>
              <div class="col-xs-6 col-md-12">
                <%= description.description %>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-1">
            <div class="row">
              <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
                <h5>UNIT</h5>
              </div>
              <div class="col-xs-6 col-md-12">
                <%= description.unit %>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-2">
            <div class="row">
              <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
                <h5>PRICE</h5>
              </div>
              <div class="col-xs-6 col-md-12">
                <%= humanized_money_with_symbol(description.price_cents) %>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-1">
            <div class="row">
              <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
                <h5>AMOUNT</h5>
              </div>
              <div class="col-xs-6 col-md-12">
                <%= description.amount %>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-1">
            <div class="row">
              <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
                <h5>VAT</h5>
              </div>
              <div class="col-xs-6 col-md-12">
                <%= description.vat_tax %>
              </div>
            </div>
          </div>
        </div>
      </div><!-- nested-fields col-xs-12 -->
    <% end %>
    <div class="nested-fields col-xs-12">
      <div class="row margin-description">
      <div class="col-xs-12 col-md-11"> <hr> </div>
        <div class="col-xs-6 col-md-6">
          <h5> TOTAL</h5>
        </div>
        <div class="hidden-xs hidden-sm">
          <div class="col-md-1"></div>
          <div class="col-md-2"></div>
          <div class="col-md-1"></div>
        </div>
        <div class="col-xs-6 col-md-1">
          <p><strong>$ 20,0</strong></p>
        </div>
      </div>
    </div><!-- nested-fields col-xs-12 -->
  </div><!-- inv-description row -->







  <!-- INFO ROW ---------------------------------- -->
  <div class="inv-info row">

    <div class="nested-fields-header col-xs-12">
      <div class="row">
        <div class="hidden-xs hidden-sm col-md-12">
          <div class="row">
            <div class="col-xs-12 col-md-5">
              <h5>INVOICE BY</h5>
            </div>
            <div class="col-xs-12 col-md-2">
              <h5>INVOICE DATE</h5>
            </div>
            <div class="col-xs-12 col-md-2">
              <h5>DUE DATE</h5>
            </div>
            <div class="col-xs-12 col-md-3">
              <h5>PAYMENT DETAILS</h5>
            </div>
          </div>
        </div>
      </div> <!-- row -->
    </div><!-- nested-fields col-xs-12 -->

    <div class="nested-fields col-xs-12">
      <div class="row">
        <div class="col-xs-12 col-md-5">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <h5>INVOICE BY</h5>
            </div>
            <div class="col-xs-6 col-md-12">
              <% if @invoice.freelancer.company_name %>
                <p><%= @invoice.freelancer.company_name %></p>
              <% else %>
                 <p><%= @invoice.freelancer.first_name %><%= @invoice.freelancer.last_name %></p>
              <% end %>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-2">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <h5>INVOICE DATE</h5>
            </div>
            <div class="col-xs-6 col-md-12">
              <p><%= @invoice.invoice_date %></p>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-2">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <h5>DUE DATE</h5>
            </div>
            <div class="col-xs-6 col-md-12">
              <p><%= @invoice.due_date %></p>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-3">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <h5>PAYMENT DETAILS</h5>
            </div>
            <div class="col-xs-12 col-md-3">
              <% if @invoice.freelancer.bank_nr %>
                 <p><%= @invoice.freelancer.bank_nr %></p>
              <% end %>
            </div>
          </div>
        </div>

      </div> <!-- row -->
    </div><!-- nested-fields col-xs-12 -->

    <div class="nested-fields-header col-xs-12">
      <div class="row">
        <div class="hidden-xs hidden-sm col-md-12">
        <div class="col-xs-12 col-md-12"><br></div>
          <div class="row">
            <div class="col-xs-12 col-md-5">
              <h5></h5>
            </div>
            <div class="col-xs-12 col-md-2">
              <h5>INVOICE NUMBER</h5>
            </div>
            <div class="col-xs-12 col-md-5">
              <h5>INVOICE TERMS</h5>
            </div>
          </div>
        </div>
      </div>
    </div><!-- nested-fields col-xs-12 -->




    <div class="nested-fields col-xs-12">
      <div class="row">
        <div class="hidden-xs hidden-sm col-md-5" >

        </div>
        <div class="col-xs-12 col-md-2">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <h5>INVOICE NUMBER</h5>
            </div>
            <div class="col-xs-6 col-md-2">
              <p><%= @invoice.invoice_nr %></p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-md-5">
          <div class="row">
            <div class="col-xs-6 visible-xs-inline-block visible-sm-inline-block">
              <h5>INVOICE TERMS</h5>
            </div>
            <div class="col-xs-6 col-md-12">
              <p><%= @invoice.invoice_terms %></p>
            </div>
          </div>
        </div>
      </div>
    </div><!-- nested-fields col-xs-12 -->

  </div><!-- inv-info row -->



</div><!-- white-paper -->

app/views/invoices/destroy.js.erb
$("#<%= @id%>").remove();

<% if @invoices.empty? %>
  $(".no-invoice").removeClass("hidden");
<% end %>

app/views/invoices/edit.html.erb
<div class="wrapper">
  <div class="container-fluid">
    <div class="row">
        <div class="form-container">
          <%= render 'form' %>
        </div>
    </div>
  </div>
</div>

app/views/invoices/edit_email.html.erb
<h3>To: <%= @invoice.client.email %></h3>
<%= form_tag send_email_invoice_path(@invoice) do %>
<h3>Subject: Invoice from <%= current_user.freelancer.first_name %></h3>

<%= text_area_tag :text, current_user.freelancer.email_text, rows: "8", cols: "100" %>
<div class="checkbox"> <label for ="save">
  <%= check_box_tag :save, 1, checked: true %>
  <p>Save this template for invoice I will be sending</p>
</label>
<div class="pull-right">
<%= submit_tag "Send the invoice", class: 'btn btn-flashy' %>
<% end %>
</div>
</div>

app/views/invoices/index.html.erb
<div class="no-invoice <%= 'hidden' unless @invoices.blank? %>">

  <div class="row">
    <div class="text-center">
      <h3><%= t('invoice.index.hello') %></h3>

      <h3><%= t('invoice.index.no-invoice') %></h3>
      <h3><%= t('invoice.index.create-1-invoice') %></h3>
      <br>
      <%= link_to t('invoice.index.btn-1-invoice') , new_invoice_path, class: "btn btn-flashy" %>
    </div>
  </div>

</div>

<% if !@invoices.blank? %>
<!-- rendering newsfeed -->
<div class="notif-wrapper">
<ul>
<%= render_activities(@activities[0..4]) %>
<div>
<%= link_to '#', id: "see-activities" do %>
<p class="text-center see-more">...See more activities...</p>
<% end %>
<div class="hidden" id="activities">
<%= render_activities(@activities[4...50]) %>
<a href="#"> <p id="hide-activities" class="text-center see-more">...Hide activities...</p></a>
</div>
</div>

</ul>

</div>

<!--  -->


<% current_user.freelancer.invoices.each do |invoice| %>
<%= link_to invoice_path(invoice) do %>
<div class="invoice-wrapper" id="<%= invoice.id %>">
 <div class="row">
  <!-- <div class="col-xs-1 col-md-1"> <%= check_box('invoice', 'validated')  %> </div> -->
  <div class="col-xs-6 col-md-2"> <%= invoice.client.first_name %> <%= invoice.client.last_name %> </div>
  <div class="col-xs-5 col-md-2"> <%= invoice.client.company %></div>
  <div class="col-xs-offset-1 col-xs-3 col-md-1 col-sm-offset-0"> <p><%= rand(100..500) %>€</p></div>
  <!-- TODO sydney change ruby interpolation to model maybe ?  -->
  <div class="col-xs-3 col-md-1"> <i> <p><%= invoice.transitions[0].nil? ? "draft" : invoice.current_state %></p> </i></div>
  <div class="col-xs-6 col-md-4"> <%= invoice.due_date.to_formatted_s(:long) %> </div>
  <div class="col-xs-offset-7 col-xs-6 col-md-2 col-sm-offset-0">
    <ul class="icons-inline">
             <!--  <li>

                 <i class="fa fa-money" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="mark as paid"></i>

               </li> -->
               <li>
                 <%= link_to edit_invoice_path(invoice) do %>
                 <i class="fa fa-pencil" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit your invoice"></i>
                 <% end %>
               </li>
               <li>
                <%= link_to edit_email_invoice_path(invoice) do %>
                <i class="fa fa-envelope" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Send your invoice"></i>
                <% end %>
              </li>
              <li>
                <%= link_to invoice_path(invoice), method: :delete, remote: true,
                data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Delete invoice"></i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>

app/views/invoices/show.html.erb
<%= render 'invoice_show' %>

<h1 class="btn btn-invoice">  <%= link_to 'Download PDF', invoice_path(@invoice, :format => :pdf), :target => '_blank' %></h1>
<h1 class="btn btn-invoice">  <%= link_to 'go back to dashboard', dashboard_path %></h1>
<h1 class="btn btn-invoice">  <%= link_to 'edit', edit_invoice_path(@invoice) %></h1>

app/views/invoices/show.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= wicked_pdf_stylesheet_link_tag "application" -%>
  </head>
  <body >
    <div id="content">
      <%= render 'pdf_invoice.html' %>
    </div>
  </body>
</html>