config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admini', as: 'rails_admin'
  get 'registrations/after_sign_up_path_for'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "registrations", invitations: "invitations" }

  authenticated :user do
    root to: 'invoices#index', as: :dashboard
  end

  root to: 'pages#home'

  resource :freelancer
  resource :client, only: [:show, :edit, :update, :destroy]

  namespace :client do
    resources :invoices, only: [:index, :show, :create] do
      resource :payment, only: [:create, :new]
    end
  end

  resources :invoices do
    member do
      get :edit_email
      post :send_email
    end
  end
  resources :pages

  authenticate :user, lambda { |u| u.admin  } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_analytics.html.erb
<!-- google analytics   -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83156328-1', 'auto');
  ga('send', 'pageview');

</script>


<!-- Hotjar Tracking Code for http://www.papaye.co -->
<!-- Allow to track user mouse and stuff for better UX, [SYD]: I invited both of you to the platform -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:273119,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container fluid-container">
    <div class="container" id="footer">
      <div class="row footer-row">
        <div class="col-xs-6 col-md-4 text-center">
          <!-- social icons -->
          <a href="#" class="li-social footer-links">
            <i class="fa fa-twitter-square" aria-hidden="true"></i>
          </a>
          <a href="#" class="li-social footer-links">
            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
          </a>
          <a href="#" class="li-social footer-links">
            <i class="fa fa-facebook-square" aria-hidden="true"></i>
          </a>
        </div>
        <div class="col-xs-6 col-md-8 footer-col">
          <span class="footer-links footer-text-links">
            <%= link_to t('shared.footer.contact-us'), 'mailto:invictus.invoice@gmail.com' %>
          </span>
<!--           <span class="footer-links footer-text-links">
            <%= link_to t('shared.footer.terms-conditions'), '#' %>
          </span> -->
          <span class="footer-links footer-text-links">
            <%= link_to t('shared.footer.team'), '#' %>
          </span>
          <style>
          </style>
        </div>
     </div>
   </div>

 <div class="copy-right">
   <p><%= t('shared.footer.copy-right') %></p>
 </div>
</div>

app/views/shared/_loginbanner.html.erb
<% quotes = [["It always seems impossible until its done.", "Nelson Mandela"],["Good, better, best. Never let it rest. 'Til your good is better and your better is best.", "St. Jerome"], ["We should not give up and we should not allow the problem to defeat us.", " A. P. J. Abdul Kalam"], ["In order to succeed, we must first believe that we can.", "Nikos Kazantzakis"], ["Always do your best. What you plant now, you will harvest later", "Og Mandino"], ["Whether you think you can, or you think you can't--you're right.", "Henry Ford"] ] %>
<% quote = quotes.sample %>

<div class="banner" id="loginbanner" style="background-image:  linear-gradient(-225deg, rgba(66, 45, 84, 0.71) 0%, rgba(14, 0, 61, 0.71) 50%), url(<%= image_path 'freelance.jpg'%>);">

  <div class="banner-content text-center">
  <div class="banner-text">
  <br>
    <h2><%= quote[0] %></h2>
    <p> <%= quote[1] %></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-invictus">
  <!-- Logo -->
  <div>
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1>Papaye</h1>
    <p>Beta</p>
  <% end %>
  </div>
  <!-- Right Navigation -->
  <div class="pull-right hidden-xs hidden-sm">
  <ul class="list-inline">
    <li><%#= link_to "About us", "#" %></li>
    <li><%= link_to t('home.banner-card-title'), "#why-wrapper" %></li>
    <li><%= link_to t(".top_call_to_action", default: "Log-in"),new_user_session_path, class: "btn btn-navbar" %></li>
  </ul>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "About us", "#" %></li>
    <li><%= link_to "Pricing", "#" %></li>
    <li><%= link_to t(".top_call_to_action", default: "My Dashboard"),new_user_session_path, class: "btn btn-navbar" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% unless current_user.client %>
  <nav class="navbar-default navbar-fixed-side hidden-xs" id="sidebar">
    <!-- normal collapsible navbar markup -->
    <br>
    <ul class="list-unstyled">
      <h3 class="sidebar-title"><%= current_user.freelancer.first_name %></h3>
       <% if user_signed_in? %>
       <li class="sidebar-nav"><%= link_to t('btn-create-invoice'), new_invoice_path, class: "btn btn-invoice"%></li>
       <li class="sidebar-nav"> <%= link_to t('dashboard'), dashboard_path, id: "navlink", class: current_link(dashboard_path) %></li>
       <li class="sidebar-nav"> <%= link_to t('settings'), edit_freelancer_path, id: "navlink", class: current_link(edit_freelancer_path) %></li>
       <li class="sidebar-nav"> <%= link_to t('profile'), freelancer_path, id: "navlink", class: current_link(freelancer_path) %></li>
    </ul>
    <div class="btn btn-navbar navlink" id="logout-freelance"> <%= link_to destroy_user_session_path,  method: :delete do %>
      <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>
    </div>
  </nav>
  <% end %>

<% else %>
  <nav class="navbar-default navbar-fixed-side hidden-xs" id="sidebar">
    <!-- normal collapsible navbar markup -->
    <br>
    <ul class="list-unstyled">
      <h3 class="sidebar-title"><%= current_user.client.first_name %></h3>
       <% if user_signed_in? %>
       <li class="sidebar-nav"> <%= link_to t('dashboard'), client_invoices_path, id: "navlink", class: current_link(client_invoices_path) %></li>
       <li class="sidebar-nav"> <%= link_to t('settings'), edit_client_path, id: "navlink", class: current_link(edit_client_path) %></li>
       <li class="sidebar-nav"> <%= link_to t('profile'), client_path, id: "navlink", class: current_link(client_path) %></li>
    </ul>
    <div class="btn btn-navbar navlink" id="logout-freelance"> <%= link_to destroy_user_session_path,  method: :delete do %>
      <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>
    </div>
  </nav>
  <% end %>
<% end %>

app/views/shared/_welcome.html.erb
<div id="welcomenavbar">

  <p id="powered-by"><%= t('shared.welcome-nav.powered') %></p>
  <div class="text-center">
    <% if current_user.nil? %>
    <h1><%= t('shared.welcome-nav.not-signed') %></h1>
    <% else %>
    <h1 id="dashboard-title"><%= t('dashboard') %></h1>
    <% end %>
  </div>
  <!-- Burger for mobile version -->
<button class="hidden-sm hidden-md hidden-lg burger" type="button" data-toggle="collapse" data-target="#collapsenavbar" aria-controls="collapsenavbar" aria-expanded="false" aria-label="Toggle navigation">
  <i class="fa fa-bars fa-2x"></i>

  </button>
<div class="burger-collapse">
  <div class="collapse navbar-toggleable-xs" id="collapsenavbar">
    <!-- normal collapsible navbar markup -->
    <br>
    <ul class="list-inline text-center">
      <% unless current_user.client %>
        <li><%= link_to t('btn-create-invoice'), new_invoice_path, class: "btn btn-invoice" %></li>
        <br>
        <li> <%= link_to t('dashboard'), dashboard_path, id: "navlink", class: current_link(dashboard_path) %></li>
        <li> <%= link_to t('settings'), edit_freelancer_path, id: "navlink", class: current_link(edit_freelancer_path) %></li>
        <li> <%= link_to t('profile'), freelancer_path, id: "navlink", class: current_link(freelancer_path) %></li>
        <li> <%= link_to t('logout'), destroy_user_session_path,  id: "navlink",method: :delete %></li>
        <hr>
      <% else %>
        <li> <%= link_to t('dashboard'), client_invoices_path, id: "navlink", class: current_link(client_invoices_path) %></li>
        <li> <%= link_to t('settings'), edit_client_path, id: "navlink", class: current_link(edit_client_path) %></li>
        <li> <%= link_to t('profile'), client_path, id: "navlink", class: current_link(client_path) %></li>
        <li> <%= link_to t('logout'), destroy_user_session_path,  id: "navlink",method: :delete %></li>
        <hr>
    <% end %>
    </ul>
  </div>
</div>
<!--  -->
</div>